
##
GET http://localhost:5000/
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2ODYxNjM5MjEsImV4cCI6MTY4NjE2Mzk1MSwiYXVkIjoiNjQ4MGIxNDA3ODZhNTQxNTFmNDAwOTcwIiwiaXNzIjoiYW5pa2V0ay5pbiJ9.OaRdm6prDt_ZgwYvlBfRdE79xPXEbs96wDGa7ddXNRg

### Login Route

POST http://localhost:5000/auth/login
content-type: application/json

{
    "email": "aniket123@aniket.com",
    "password": "hello"
}


### Register Route

POST http://localhost:5000/auth/register
content-type: application/json

{
    "email": "aniket1233@aniket.com",
    "password": "hello"
}

### Refresh Token Route

POST http://localhost:5000/auth/refresh-token
Content-Type: application/json

{
    "refresh_token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2ODYxNzExNzEsImV4cCI6MTcxNzcyODc3MSwiYXVkIjoiNjQ4MGVlMjIyNWYxYzE4NjU5ODNkYTc1IiwiaXNzIjoiYW5pa2V0ay5pbiJ9.DFQ9Xj1qAs7R8auOE9xyLzqhZopZn25fI5lOEqPae1I"
}

### Refresh Token Route

DELETE http://localhost:5000/auth/logout
Content-Type: application/json

{
    "refresh_token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2ODYxNzExODYsImV4cCI6MTcxNzcyODc4NiwiYXVkIjoiNjQ4MGVlMjIyNWYxYzE4NjU5ODNkYTc1IiwiaXNzIjoiYW5pa2V0ay5pbiJ9.O7q6CZX48_-JMYrUa5G0GUaET-BcUTF2BM2HjaY3fs4"
}